export const NADEO_NAME_LIMIT = 15;
export const BINGO_ROOM_IDENTIFIER_LENGTH = 3;
export const DEFAULT_OAUTH_ACCESS_TOKEN_LIFETIME_MS = 60 * 60 * 1000;
export const DEFAULT_DEV_ACCESS_TOKEN_LIFETIME_MS = 15 * 60 * 1000;
