function Get-XjkLearnProfileEnvironmentBindings {
  return @(
    "LEARN_UBI_OAUTH_ENABLED",
    "LEARN_UBI_OAUTH_CLIENT_ID",
    "LEARN_UBI_OAUTH_CLIENT_SECRET",
    "LEARN_UBI_OAUTH_AUTHORIZE_URL",
    "LEARN_UBI_OAUTH_TOKEN_URL",
    "LEARN_UBI_OAUTH_USERINFO_URL",
    "LEARN_UBI_OAUTH_SCOPE",
    "LEARN_UBI_OAUTH_CALLBACK_PATH",
    "LEARN_SESSION_COOKIE_NAME",
    "LEARN_SESSION_TTL_SECONDS",
    "LEARN_OAUTH_STATE_TTL_SECONDS",
    "LEARN_PROFILE_USER_AGENT",
    "LEARN_PROFILE_REQUEST_TIMEOUT_MS",
    "LEARN_CONTENT_DIR",
    "LEARN_HEAD_ADMIN_SUBJECTS",
    "LEARN_HEAD_ADMIN_USERNAMES",
    "LEARN_EDITOR_SUBJECTS",
    "LEARN_EDITOR_USERNAMES"
  )
}

function Get-XjkAlteredEnvironmentBindings {
  return @(
    "ALTERED_ADMIN_TOKEN",
    "TRACKER_ADMIN_USERNAME",
    "TRACKER_ADMIN_PASSWORD",
    "TRACKER_LEADERBOARD_PUBLIC_BASE_URL",
    "TRACKER_LEADERBOARD_ADMIN_BASE_URL",
    "TRACKER_LEADERBOARD_ADMIN_TOKEN",
    "TRACKER_LEADERBOARD_ADMIN_USERNAME",
    "TRACKER_LEADERBOARD_ADMIN_PASSWORD",
    "TRACKER_DISPLAYNAME_BASE_URL",
    "TRACKER_CLUB_BASE_URL",
    "AGGREGATOR_BASE_URL",
    @{ Key = "AGGREGATOR_TOKEN"; SourceKey = "AGGREGATOR_INGEST_TOKEN" },
    "AGGREGATOR_TOKEN",
    "ALTERED_TRACKER_DISPLAYNAME_ENABLED",
    "ALTERED_TRACKER_DISPLAYNAME_FALLBACK_LOCAL",
    "ALTERED_TRACKER_CLUB_ENABLED",
    "ALTERED_TRACKER_CLUB_FALLBACK_LOCAL",
    "UBI_OAUTH_ENABLED",
    "UBI_OAUTH_CLIENT_ID",
    "UBI_OAUTH_CLIENT_SECRET",
    "UBI_OAUTH_AUTHORIZE_URL",
    "UBI_OAUTH_TOKEN_URL",
    "UBI_OAUTH_USERINFO_URL",
    "UBI_OAUTH_SCOPE",
    "UBI_OAUTH_CALLBACK_PATH",
    "UBI_OAUTH_ALLOWED_SUBJECTS",
    "UBI_OAUTH_ALLOWED_USERNAMES",
    "ALTERED_SESSION_COOKIE_NAME",
    "ALTERED_SESSION_TTL_SECONDS",
    "ALTERED_OAUTH_STATE_TTL_SECONDS",
    "ALTERED_OAUTH_FALLBACK_LOCAL_ONLY",
    "ALTERED_LIVE_MONITOR_ENABLED",
    "ALTERED_LIVE_MONITOR_INTERVAL_SECONDS",
    "ALTERED_LIVE_CLUB_ID",
    "ALTERED_LIVE_ACTIVITY_PAGE_SIZE",
    "ALTERED_LIVE_ACTIVITY_ACTIVE_ONLY",
    "ALTERED_LIVE_FETCH_MAP_DETAILS",
    "ALTERED_LIVE_AUTH_MODE",
    @{ Key = "ALTERED_LIVE_AUTH_MODE"; SourceKey = "TRACKER_NADEO_AUTH_MODE" },
    "ALTERED_LIVE_DEDI_LOGIN",
    @{ Key = "ALTERED_LIVE_DEDI_LOGIN"; SourceKey = "TRACKER_NADEO_DEDI_LOGIN" },
    "ALTERED_LIVE_DEDI_PASSWORD",
    @{ Key = "ALTERED_LIVE_DEDI_PASSWORD"; SourceKey = "TRACKER_NADEO_DEDI_PASSWORD" },
    "ALTERED_LIVE_ACCESS_TOKEN",
    @{ Key = "ALTERED_LIVE_ACCESS_TOKEN"; SourceKey = "TRACKER_NADEO_LIVE_ACCESS_TOKEN" },
    "ALTERED_LIVE_REFRESH_TOKEN",
    @{ Key = "ALTERED_LIVE_REFRESH_TOKEN"; SourceKey = "TRACKER_NADEO_LIVE_REFRESH_TOKEN" },
    "ALTERED_LIVE_API_BASE_URL",
    "ALTERED_LIVE_USER_AGENT",
    "ALTERED_LIVE_REQUEST_TIMEOUT_MS",
    @{ Key = "ALTERED_LIVE_REQUEST_TIMEOUT_MS"; SourceKey = "TRACKER_REQUEST_TIMEOUT_MS" },
    "ALTERED_LIVE_MIN_REQUEST_GAP_MS",
    "ALTERED_OPS_MONITOR_ENABLED",
    "ALTERED_OPS_MONITOR_TICK_SECONDS",
    "ALTERED_OPS_MONITOR_MAX_MAPS_PER_RUN"
  )
}

function Get-XjkTrackerEnvironmentBindings {
  return @(
    "ALTERED_ADMIN_TOKEN",
    "TRACKER_ADMIN_USERNAME",
    "TRACKER_ADMIN_PASSWORD",
    "TRACKER_ADMIN_SESSION_COOKIE_NAME",
    "TRACKER_ADMIN_SESSION_TTL_SECONDS",
    "TRACKER_ADMIN_ALLOW_OPEN",
    "TRACKER_ENABLED",
    "TRACKER_MODE",
    "TRACKER_LEADERBOARD_TOP_N",
    "TRACKER_PROVIDER",
    "TRACKER_NADEO_AUTH_MODE",
    "TRACKER_NADEO_DEDI_LOGIN",
    "TRACKER_NADEO_DEDI_PASSWORD",
    "TRACKER_UBI_EMAIL",
    "TRACKER_UBI_PASSWORD",
    "TRACKER_NADEO_LIVE_ACCESS_TOKEN",
    "TRACKER_NADEO_LIVE_REFRESH_TOKEN",
    "TRACKER_TOKEN_CACHE_FILE",
    "TRACKER_LIVE_GROUP_UID",
    "TRACKER_LIVE_ONLY_WORLD",
    "TRACKER_REQUEST_TIMEOUT_MS",
    "TRACKER_MIN_REQUEST_GAP_MS",
    "TRACKER_USER_AGENT",
    "TRACKER_WR_WEBHOOK_ENABLED",
    "TRACKER_WR_WEBHOOK_URL",
    "TRACKER_WR_WEBHOOK_TIMEOUT_MS",
    "TRACKER_AGGREGATOR_ENABLED",
    "TRACKER_AGGREGATOR_BASE_URL",
    @{ Key = "TRACKER_AGGREGATOR_TOKEN"; SourceKey = "AGGREGATOR_INGEST_TOKEN" },
    "TRACKER_AGGREGATOR_TOKEN",
    "TRACKER_AGGREGATOR_PROJECT_KEY",
    "TRACKER_AGGREGATOR_PROJECT_NAME",
    "TRACKER_AGGREGATOR_SOURCE_LABEL",
    "TRACKER_AGGREGATOR_TIMEOUT_MS",
    "TRACKER_INSTANCE_ID",
    "TRACKER_INSTANCE_NAME"
  )
}

function Get-XjkTrackerLeaderboardEnvironmentBindings {
  return @(
    "TRACKER_ADMIN_USERNAME",
    "TRACKER_ADMIN_PASSWORD",
    "TRACKER_ADMIN_SESSION_COOKIE_NAME",
    "TRACKER_ADMIN_SESSION_TTL_SECONDS",
    "TRACKER_ADMIN_ALLOW_OPEN",
    "TRACKER_ENABLED",
    "TRACKER_MODE",
    "TRACKER_LEADERBOARD_TOP_N",
    "TRACKER_PROVIDER",
    "TRACKER_TICK_SECONDS",
    "TRACKER_BATCH_SIZE",
    "TRACKER_MAX_CHECK_INTERVAL_SECONDS",
    "TRACKER_NADEO_AUTH_MODE",
    "TRACKER_NADEO_DEDI_LOGIN",
    "TRACKER_NADEO_DEDI_PASSWORD",
    "TRACKER_NADEO_LIVE_ACCESS_TOKEN",
    "TRACKER_NADEO_LIVE_REFRESH_TOKEN",
    "TRACKER_TOKEN_CACHE_FILE",
    "TRACKER_LIVE_GROUP_UID",
    "TRACKER_LIVE_ONLY_WORLD",
    "TRACKER_REQUEST_TIMEOUT_MS",
    "TRACKER_MIN_REQUEST_GAP_MS",
    "TRACKER_USER_AGENT",
    "TRACKER_WR_WEBHOOK_ENABLED",
    "TRACKER_WR_WEBHOOK_URL",
    "TRACKER_WR_WEBHOOK_TIMEOUT_MS",
    "TRACKER_AGGREGATOR_ENABLED",
    "TRACKER_AGGREGATOR_BASE_URL",
    @{ Key = "TRACKER_AGGREGATOR_TOKEN"; SourceKey = "AGGREGATOR_INGEST_TOKEN" },
    "TRACKER_AGGREGATOR_TOKEN",
    "TRACKER_AGGREGATOR_PROJECT_KEY",
    "TRACKER_AGGREGATOR_PROJECT_NAME",
    "TRACKER_AGGREGATOR_SOURCE_LABEL",
    "TRACKER_AGGREGATOR_TIMEOUT_MS",
    "TRACKER_INSTANCE_ID",
    "TRACKER_INSTANCE_NAME"
  )
}

function Get-XjkAggregatorEnvironmentBindings {
  return @(
    "AGGREGATOR_INGEST_TOKEN",
    "DASH_ADMIN_TOKEN",
    "DASH_HOSTNAMES",
    "DASH_TRACKER_WR_BASE_URL",
    "DASH_TRACKER_LEADERBOARD_BASE_URL",
    "DASH_TRACKER_DISPLAYNAME_BASE_URL",
    "DASH_TRACKER_CLUB_BASE_URL"
  )
}

function Get-XjkTrackerDisplayNameEnvironmentBindings {
  return @(
    @{ Key = "AGGREGATOR_INGEST_TOKEN"; SourceKey = "TRACKER_DISPLAYNAME_AGGREGATOR_TOKEN" },
    @{ Key = "AGGREGATOR_INGEST_TOKEN"; SourceKey = "TRACKER_AGGREGATOR_TOKEN" },
    @{ Key = "TRACKER_DISPLAYNAME_AGGREGATOR_TOKEN"; SourceKey = "AGGREGATOR_INGEST_TOKEN" },
    "TRACKER_DISPLAYNAME_AGGREGATOR_TOKEN",
    "TRACKER_DISPLAYNAME_ENABLED",
    "TRACKER_DISPLAYNAME_SCHEDULER_ENABLED",
    "TRACKER_DISPLAYNAME_MAINTENANCE_INTERVAL_SECONDS",
    "TRACKER_DISPLAYNAME_STALE_AFTER_SECONDS",
    "TRACKER_DISPLAYNAME_BATCH_SIZE",
    "TRACKER_DISPLAYNAME_MAX_ACCOUNTS_PER_CYCLE",
    "TRACKER_DISPLAYNAME_REQUEST_TIMEOUT_MS",
    "TRACKER_DISPLAYNAME_MIN_REQUEST_GAP_MS",
    "TRACKER_DISPLAYNAME_PROJECT_KEY",
    "TRACKER_DISPLAYNAME_PROJECT_NAME",
    "TRACKER_DISPLAYNAME_SOURCE_LABEL",
    "TRACKER_DISPLAYNAME_API_BASE_URL",
    "TRACKER_DISPLAYNAME_SCOPE",
    "TRACKER_DISPLAYNAME_USER_AGENT",
    "UBI_OAUTH_CLIENT_ID",
    "UBI_OAUTH_CLIENT_SECRET",
    "UBI_OAUTH_TOKEN_URL"
  )
}

function Get-XjkTrackerClubEnvironmentBindings {
  return @(
    @{ Key = "TRACKER_CLUB_AGGREGATOR_TOKEN"; SourceKey = "AGGREGATOR_INGEST_TOKEN" },
    "TRACKER_CLUB_AGGREGATOR_TOKEN",
    "TRACKER_CLUB_ENABLED",
    "TRACKER_CLUB_PROJECT_KEY",
    "TRACKER_CLUB_PROJECT_NAME",
    "TRACKER_CLUB_SOURCE_LABEL",
    "TRACKER_CLUB_REQUEST_TIMEOUT_MS"
  )
}

function Set-XjkLocalBackendEnvironmentBindings {
  param(
    [hashtable]$BackendByName,
    [hashtable]$AlteredDotEnv,
    [hashtable]$TrackerDotEnv,
    [hashtable]$LearnProfileDotEnv
  )

  $bindingSets = @(
    @{ Name = "learn-profile"; Bindings = @(Get-XjkLearnProfileEnvironmentBindings); DotEnv = $LearnProfileDotEnv },
    @{ Name = "altered-hub"; Bindings = @(Get-XjkAlteredEnvironmentBindings) },
    @{ Name = "tracker-hub"; Bindings = @(Get-XjkTrackerEnvironmentBindings) },
    @{ Name = "tracker-aggregator"; Bindings = @(Get-XjkAggregatorEnvironmentBindings) },
    @{ Name = "tracker-displayname"; Bindings = @(Get-XjkTrackerDisplayNameEnvironmentBindings) },
    @{ Name = "tracker-club"; Bindings = @(Get-XjkTrackerClubEnvironmentBindings) },
    @{ Name = "tracker-leaderboard"; Bindings = @(Get-XjkTrackerLeaderboardEnvironmentBindings) }
  )
  foreach ($bindingSet in $bindingSets) {
    $backend = $BackendByName[[string]$bindingSet.Name]
    Set-XjkEnvironmentBindings `
      -Environment $backend.Env `
      -Bindings $bindingSet.Bindings `
      -FromProcessEnvironment
    if ($bindingSet.DotEnv) {
      Set-XjkEnvironmentBindings `
        -Environment $backend.Env `
        -Bindings $bindingSet.Bindings `
        -SourceMap $bindingSet.DotEnv
    }
  }

  Set-XjkEnvironmentBindings `
    -Environment $BackendByName["altered-hub"].Env `
    -Bindings @(
      "TRACKER_ADMIN_USERNAME",
      "TRACKER_ADMIN_PASSWORD",
      @{ Key = "TRACKER_LEADERBOARD_ADMIN_TOKEN"; SourceKey = "TRACKER_ADMIN_TOKEN" },
      @{ Key = "TRACKER_LEADERBOARD_ADMIN_USERNAME"; SourceKey = "TRACKER_ADMIN_USERNAME" },
      @{ Key = "TRACKER_LEADERBOARD_ADMIN_PASSWORD"; SourceKey = "TRACKER_ADMIN_PASSWORD" }
    ) `
    -SourceMap $TrackerDotEnv

  Set-XjkEnvironmentBindings `
    -Environment $BackendByName["tracker-displayname"].Env `
    -Bindings @(
      @{ Key = "TRACKER_DISPLAYNAME_API_BASE_URL"; SourceKey = "ALTERED_MAPPER_NAME_TRACKING_API_BASE_URL" },
      @{ Key = "TRACKER_DISPLAYNAME_SCOPE"; SourceKey = "ALTERED_MAPPER_NAME_TRACKING_SCOPE" },
      @{ Key = "TRACKER_DISPLAYNAME_USER_AGENT"; SourceKey = "ALTERED_MAPPER_NAME_TRACKING_USER_AGENT" },
      "UBI_OAUTH_CLIENT_ID",
      "UBI_OAUTH_CLIENT_SECRET",
      @{ Key = "UBI_OAUTH_TOKEN_URL"; SourceKey = "ALTERED_MAPPER_NAME_TRACKING_TOKEN_URL" },
      "UBI_OAUTH_TOKEN_URL"
    ) `
    -SourceMap $AlteredDotEnv
}

function Get-XjkBackendEnvironmentValidationBindings {
  return @(
    @{ Name = "altered-hub"; Key = "ALTERED_OPS_MONITOR_ENABLED"; SourceKey = "ALTERED_OPS_MONITOR_ENABLED" },
    @{ Name = "tracker-hub"; Key = "TRACKER_UBI_EMAIL"; SourceKey = "TRACKER_UBI_EMAIL" },
    @{ Name = "tracker-aggregator"; Key = "DASH_ADMIN_TOKEN"; SourceKey = "DASH_ADMIN_TOKEN" },
    @{ Name = "tracker-displayname"; Key = "TRACKER_DISPLAYNAME_ENABLED"; SourceKey = "TRACKER_DISPLAYNAME_ENABLED" },
    @{ Name = "tracker-club"; Key = "TRACKER_CLUB_ENABLED"; SourceKey = "TRACKER_CLUB_ENABLED" },
    @{ Name = "validifier-public"; Key = "VALIDIFIER_INTERNAL_BASE_URL"; SourceKey = "VALIDIFIER_INTERNAL_BASE_URL" },
    @{ Name = "validifier-public"; Key = "VALIDIFIER_INTERNAL_ACCESS_TOKEN"; SourceKey = "VALIDIFIER_INTERNAL_ACCESS_TOKEN" },
    @{ Name = "validifier-public"; Key = "VALIDIFIER_INTERNAL_SUBMISSION_SECRET"; SourceKey = "VALIDIFIER_INTERNAL_SUBMISSION_SECRET" }
  )
}
