function createAccountState() {
  return {
    activeTab: "overview",
    activeSpace: "",
    sessionPayload: null,
    preferences: null,
    profileImage: "",
    nicknames: {},
    editingNickname: false,
    dirty: false,
    logoutBusy: false,
    sessionActionError: "",
  };
}

function collectAccountElements(doc = document) {
  return {
    heroSessionLine: doc.getElementById("heroSessionLine"),
    tabButtons: [...doc.querySelectorAll("[data-tab-target]")],
    panels: {
      overview: doc.getElementById("panel-overview"),
      appearance: doc.getElementById("panel-appearance"),
      spaces: doc.getElementById("panel-spaces"),
    },
    jumpButtons: [...doc.querySelectorAll("[data-jump-tab]")],
    spacePills: doc.getElementById("spacePills"),
    overviewMeta: doc.getElementById("overviewMeta"),
    appearanceMeta: doc.getElementById("appearanceMeta"),
    sessionStateValue: doc.getElementById("sessionStateValue"),
    overviewSessionState: doc.getElementById("overviewSessionState"),
    overviewSessionExpires: doc.getElementById("overviewSessionExpires"),
    overviewAccessLevel: doc.getElementById("overviewAccessLevel"),
    overviewAdminRow: doc.getElementById("overviewAdminRow"),
    identityMemberSince: doc.getElementById("identityMemberSince"),
    identityLastActive: doc.getElementById("identityLastActive"),
    overviewProfileAvatar: doc.getElementById("overviewProfileAvatar"),
    overviewProfileImage: doc.getElementById("overviewProfileImage"),
    overviewAvatarInput: doc.getElementById("overviewAvatarInput"),
    overviewAvatarNote: doc.getElementById("overviewAvatarNote"),
    nicknameEditButton: doc.getElementById("nicknameEditButton"),
    nicknameForm: doc.getElementById("nicknameForm"),
    nicknameInput: doc.getElementById("nicknameInput"),
    nicknameCancelButton: doc.getElementById("nicknameCancelButton"),
    nicknameResetButton: doc.getElementById("nicknameResetButton"),
    identityDisplayName: doc.getElementById("identityDisplayName"),
    identityUsername: doc.getElementById("identityUsername"),
    identityXjkIdDetail: doc.getElementById("identityXjkIdDetail"),
    identityUbisoftIdDetail: doc.getElementById("identityUbisoftIdDetail"),
    identityRolesDetail: doc.getElementById("identityRolesDetail"),
    loginButton: doc.getElementById("loginButton"),
    overviewLogoutButton: doc.getElementById("overviewLogoutButton"),
    overviewActionNote: doc.getElementById("overviewActionNote"),
    appearanceAccent: doc.getElementById("appearanceAccent"),
    appearanceDensity: doc.getElementById("appearanceDensity"),
    appearanceMotion: doc.getElementById("appearanceMotion"),
    accentSwatches: doc.getElementById("accentSwatches"),
    accentReadout: doc.getElementById("accentReadout"),
    densitySegments: doc.getElementById("densitySegments"),
    densityReadout: doc.getElementById("densityReadout"),
    motionSegments: doc.getElementById("motionSegments"),
    motionReadout: doc.getElementById("motionReadout"),
    appearanceStatusPill: doc.getElementById("appearanceStatusPill"),
    appearancePreviewTitle: doc.getElementById("appearancePreviewTitle"),
    appearancePreviewMeta: doc.getElementById("appearancePreviewMeta"),
    appearanceSaveStateValue: doc.getElementById("appearanceSaveStateValue"),
    appearanceStorageValue: doc.getElementById("appearanceStorageValue"),
    appearanceUpdatedValue: doc.getElementById("appearanceUpdatedValue"),
    appearanceActiveValue: doc.getElementById("appearanceActiveValue"),
    saveAppearanceButton: doc.getElementById("saveAppearanceButton"),
    resetAppearanceButton: doc.getElementById("resetAppearanceButton"),
    appearanceHint: doc.getElementById("appearanceHint"),
    downloadSnapshotButtonData: doc.getElementById("downloadSnapshotButtonData"),
    clearPreferencesButton: doc.getElementById("clearPreferencesButton"),
    sessionPayload: doc.getElementById("sessionPayload"),
    spacePanelTitle: doc.getElementById("spacePanelTitle"),
    spacePanelMeta: doc.getElementById("spacePanelMeta"),
    spaceSummaryCard: doc.querySelector(".space-summary"),
    spaceSummaryIcon: doc.getElementById("spaceSummaryIcon"),
    spaceSummaryTitle: doc.getElementById("spaceSummaryTitle"),
    spaceSummaryText: doc.getElementById("spaceSummaryText"),
    spaceLoginMode: doc.getElementById("spaceLoginMode"),
    spaceSettingsMode: doc.getElementById("spaceSettingsMode"),
    spaceRoleMode: doc.getElementById("spaceRoleMode"),
    spaceNote: doc.getElementById("spaceNote"),
    spaceRouteCard: doc.querySelector(".space-route-card"),
    spaceRouteTitle: doc.getElementById("spaceRouteTitle"),
    spaceRouteText: doc.getElementById("spaceRouteText"),
    spaceRouteHost: doc.getElementById("spaceRouteHost"),
    spaceOpenLink: doc.getElementById("spaceOpenLink"),
    spaceJumpAccountButton: doc.getElementById("spaceJumpAccountButton"),
  };
}

export { collectAccountElements, createAccountState };
