const CONTENT_SIGNATURE_VERSION = "gbx-layout-v2";
const ASSET_FALLBACK_SIGNATURE_VERSION = "asset-token-jaccard-v1-fallback";
const CONTENT_SIMILARITY_PATTERN = `content-similarity:${CONTENT_SIGNATURE_VERSION}`;

export { ASSET_FALLBACK_SIGNATURE_VERSION, CONTENT_SIGNATURE_VERSION, CONTENT_SIMILARITY_PATTERN };
