import { fileURLToPath } from "node:url";

const DEFAULT_TRACKER_SYNC_CHUNK_SIZE = 350;
const DEFAULT_DAILY_HOUR_UTC = 3;
const DEFAULT_DAILY_MINUTE_UTC = 0;
const DEFAULT_DISCOVERY_INTERVAL_SECONDS = 3600;
const DEFAULT_DISCOVERY_CAMPAIGN_LIMIT = 25;
const DEFAULT_DISCOVERY_ACTIVITY_PAGE_SIZE = 100;
const DEFAULT_MAPPER_BOOTSTRAP_INTERVAL_SECONDS = 60;
const DEFAULT_MAPPER_MAINTENANCE_INTERVAL_SECONDS = 60;
const DEFAULT_MAPPER_PRIORITY_INTERVAL_SECONDS = 60;
const DEFAULT_MAPPER_SYNC_BATCH_SIZE = 50;
const DEFAULT_MAPPER_PRIORITY_BATCH_SIZE = 25;
const DEFAULT_MAPPER_PRIORITY_TOP_LIMIT = 250;
const DEFAULT_MAPPER_PRIORITY_REFRESH_SECONDS = 600;
const DEFAULT_MAPPER_REQUEST_GAP_MS = 5000;
const DISPLAY_NAME_CACHE_TTL_SECONDS = 14 * 24 * 60 * 60;
const DEFAULT_MAPPER_CACHE_TTL_SECONDS = DISPLAY_NAME_CACHE_TTL_SECONDS;
const DEFAULT_MAPPER_PRIORITY_CACHE_TTL_SECONDS = 1800;
const DEFAULT_MAPPER_KNOWN_ACCOUNTS_REFRESH_SECONDS = 900;
const VIEW_PRIORITY_ACCOUNT_TTL_MS = 5 * 60 * 1000;
const VIEW_PRIORITY_RELAY_KICKOFF_COOLDOWN_MS = 15 * 1000;
const MAP_CONTENT_DOWNLOAD_TIMEOUT_MS = 25000;
const DEFAULT_MAP_COPY_BACKFILL_BATCH_SIZE = 250;
const DEFAULT_MAP_COPY_MAX_CONCURRENT_DOWNLOADS = 4;
const DEFAULT_MAP_COPY_BOOT_AUTO_START_MAX_PENDING = 500;
const GLOBAL_REFERENCE_FALLBACK_MAX_MAPS = 200;
const GLOBAL_REFERENCE_FALLBACK_MAX_CAMPAIGNS = 8;
const NAMING_SIMILARITY_PROGRESS_MATCHING_START = 30;
const NAMING_SIMILARITY_PROGRESS_MATCHING_SPAN = 55;
const EXTERNAL_NAMING_SIMILARITY_BATCH_SIZE = 250;
const EXTERNAL_NAMING_SIMILARITY_MIN_MAPS = 500;
const EXTERNAL_NAMING_SIMILARITY_RUNNING_GRACE_MS = 2 * 60 * 1000;
const NAMING_SIMILARITY_PROGRESS_FILE_NAME = "similarity-resolver-progress.json";
const NAMING_SIMILARITY_MAP_UIDS_FILE_NAME = "similarity-resolver-map-uids.json";
const NAMING_SIMILARITY_RESOLVER_SCRIPT_PATH = fileURLToPath(
  new URL("../../../tools/run-similarity-resolver.mjs", import.meta.url)
);
const WEEKLY_SHORTS_SOURCE_KEY = "weekly-shorts";
const WEEKLY_SHORTS_SOURCE_LABEL = "altered-weekly-shorts";
const WEEKLY_SHORTS_SOURCE_DISPLAY_NAME = "Weekly Shorts";
const WEEKLY_SHORTS_SOURCE_TYPE = "weekly-shorts";
const WEEKLY_SHORTS_CAMPAIGN_TYPE = "weekly-shorts";
const OFFICIAL_SEASONAL_SOURCE_KEY = "official-seasonal-v2";
const OFFICIAL_SEASONAL_SOURCE_LABEL = "official-seasonal-v2";
const OFFICIAL_SEASONAL_SOURCE_DISPLAY_NAME = "Official Seasonal Campaigns";
const OFFICIAL_SEASONAL_SOURCE_TYPE = "official-seasonal";
const OFFICIAL_SEASONAL_CAMPAIGN_TYPE = "official-seasonal";
const TOTD_SOURCE_KEY = "official-totd";
const TOTD_SOURCE_LABEL = "official-totd";
const TOTD_SOURCE_DISPLAY_NAME = "Track of the Day";
const TOTD_SOURCE_TYPE = "official-totd";
const TOTD_CAMPAIGN_TYPE = "official-totd";
const WEEKLY_GRANDS_SOURCE_KEY = "weekly-grands";
const WEEKLY_GRANDS_SOURCE_LABEL = "weekly-grands";
const WEEKLY_GRANDS_SOURCE_DISPLAY_NAME = "Weekly Grands";
const WEEKLY_GRANDS_SOURCE_TYPE = "weekly-grands";
const WEEKLY_GRANDS_CAMPAIGN_TYPE = "weekly-grands";
const COMPETITION_SOURCE_KEY = "official-competition";
const COMPETITION_SOURCE_LABEL = "official-competition";
const COMPETITION_SOURCE_DISPLAY_NAME = "Official Competition Maps";
const COMPETITION_SOURCE_TYPE = "official-competition";
const COMPETITION_CAMPAIGN_TYPE = "official-competition";
const COMPETITION_SOURCE_CLUB_ID = 79122;
const DISCOVERY_SOURCE_KEY = "official-discovery";
const DISCOVERY_SOURCE_LABEL = "official-discovery";
const DISCOVERY_SOURCE_DISPLAY_NAME = "Official Discovery Campaigns";
const DISCOVERY_SOURCE_TYPE = "official-discovery";
const DISCOVERY_CAMPAIGN_TYPE = "official-discovery";
const DISCOVERY_SOURCE_CLUB_ID = 150;
const DISCOVERY_SOURCE_CAMPAIGNS = [
  { campaignId: 55779, name: "Snow Discovery" },
  { campaignId: 61394, name: "Rally Discovery" },
  { campaignId: 68071, name: "Desert Discovery" },
  { campaignId: 71524, name: "Stunt Discovery" },
  { campaignId: 78488, name: "Platform Discovery" },
];
const LEGACY_SOURCE_KEY = "official-legacy";
const LEGACY_SOURCE_LABEL = "official-legacy";
const LEGACY_SOURCE_DISPLAY_NAME = "Official Legacy Campaigns";
const LEGACY_SOURCE_TYPE = "official-legacy";
const LEGACY_CAMPAIGN_TYPE = "official-legacy";
const LEGACY_SOURCE_CLUB_ID = 132907;
const LEGACY_SOURCE_CAMPAIGNS = [
  { campaignId: 130429, name: "Spring 2020" },
  { campaignId: 130430, name: "Training" },
];
const OFFICIAL_SEASONAL_SOURCE_MAX_AGE_MS = 6 * 60 * 60 * 1000;
const PROJECT_SOURCE_RELEASE_BUFFER_MS = 10 * 60 * 1000;
const PROJECT_SOURCE_SCHEDULES = {
  [OFFICIAL_SEASONAL_SOURCE_KEY]: {
    checkpointsMs: [
      PROJECT_SOURCE_RELEASE_BUFFER_MS,
      24 * 60 * 60 * 1000 + PROJECT_SOURCE_RELEASE_BUFFER_MS,
      5 * 24 * 60 * 60 * 1000 + PROJECT_SOURCE_RELEASE_BUFFER_MS,
      14 * 24 * 60 * 60 * 1000 + PROJECT_SOURCE_RELEASE_BUFFER_MS,
    ],
    followEndTimestamp: true,
  },
  [TOTD_SOURCE_KEY]: {
    checkpointsMs: [PROJECT_SOURCE_RELEASE_BUFFER_MS, 24 * 60 * 60 * 1000 + PROJECT_SOURCE_RELEASE_BUFFER_MS],
    followEndTimestamp: true,
  },
  [WEEKLY_GRANDS_SOURCE_KEY]: {
    checkpointsMs: [PROJECT_SOURCE_RELEASE_BUFFER_MS, 24 * 60 * 60 * 1000 + PROJECT_SOURCE_RELEASE_BUFFER_MS],
    followEndTimestamp: true,
  },
  [WEEKLY_SHORTS_SOURCE_KEY]: {
    checkpointsMs: [PROJECT_SOURCE_RELEASE_BUFFER_MS, 24 * 60 * 60 * 1000 + PROJECT_SOURCE_RELEASE_BUFFER_MS],
    followEndTimestamp: true,
  },
};
const DEFAULT_WEEKLY_SHORTS_IMPORT_WEEKS = [1, 2, 3, 4, 29];
const NAMING_SIMILARITY_SOURCE_OPTIONS = [
  { key: "", label: "All Sources" },
  { key: OFFICIAL_SEASONAL_SOURCE_KEY, label: "Seasonal" },
  { key: TOTD_SOURCE_KEY, label: "TOTD" },
  { key: WEEKLY_SHORTS_SOURCE_KEY, label: "Weekly Shorts" },
  { key: WEEKLY_GRANDS_SOURCE_KEY, label: "Weekly Grands" },
  { key: DISCOVERY_SOURCE_KEY, label: "Discovery" },
  { key: COMPETITION_SOURCE_KEY, label: "Competition" },
  { key: LEGACY_SOURCE_KEY, label: "Legacy" },
];

export {
  DEFAULT_TRACKER_SYNC_CHUNK_SIZE,
  DEFAULT_DAILY_HOUR_UTC,
  DEFAULT_DAILY_MINUTE_UTC,
  DEFAULT_DISCOVERY_INTERVAL_SECONDS,
  DEFAULT_DISCOVERY_CAMPAIGN_LIMIT,
  DEFAULT_DISCOVERY_ACTIVITY_PAGE_SIZE,
  DEFAULT_MAPPER_BOOTSTRAP_INTERVAL_SECONDS,
  DEFAULT_MAPPER_MAINTENANCE_INTERVAL_SECONDS,
  DEFAULT_MAPPER_PRIORITY_INTERVAL_SECONDS,
  DEFAULT_MAPPER_SYNC_BATCH_SIZE,
  DEFAULT_MAPPER_PRIORITY_BATCH_SIZE,
  DEFAULT_MAPPER_PRIORITY_TOP_LIMIT,
  DEFAULT_MAPPER_PRIORITY_REFRESH_SECONDS,
  DEFAULT_MAPPER_REQUEST_GAP_MS,
  DISPLAY_NAME_CACHE_TTL_SECONDS,
  DEFAULT_MAPPER_CACHE_TTL_SECONDS,
  DEFAULT_MAPPER_PRIORITY_CACHE_TTL_SECONDS,
  DEFAULT_MAPPER_KNOWN_ACCOUNTS_REFRESH_SECONDS,
  VIEW_PRIORITY_ACCOUNT_TTL_MS,
  VIEW_PRIORITY_RELAY_KICKOFF_COOLDOWN_MS,
  MAP_CONTENT_DOWNLOAD_TIMEOUT_MS,
  DEFAULT_MAP_COPY_BACKFILL_BATCH_SIZE,
  DEFAULT_MAP_COPY_MAX_CONCURRENT_DOWNLOADS,
  DEFAULT_MAP_COPY_BOOT_AUTO_START_MAX_PENDING,
  GLOBAL_REFERENCE_FALLBACK_MAX_MAPS,
  GLOBAL_REFERENCE_FALLBACK_MAX_CAMPAIGNS,
  NAMING_SIMILARITY_PROGRESS_MATCHING_START,
  NAMING_SIMILARITY_PROGRESS_MATCHING_SPAN,
  EXTERNAL_NAMING_SIMILARITY_BATCH_SIZE,
  EXTERNAL_NAMING_SIMILARITY_MIN_MAPS,
  EXTERNAL_NAMING_SIMILARITY_RUNNING_GRACE_MS,
  NAMING_SIMILARITY_PROGRESS_FILE_NAME,
  NAMING_SIMILARITY_MAP_UIDS_FILE_NAME,
  NAMING_SIMILARITY_RESOLVER_SCRIPT_PATH,
  WEEKLY_SHORTS_SOURCE_KEY,
  WEEKLY_SHORTS_SOURCE_LABEL,
  WEEKLY_SHORTS_SOURCE_DISPLAY_NAME,
  WEEKLY_SHORTS_SOURCE_TYPE,
  WEEKLY_SHORTS_CAMPAIGN_TYPE,
  OFFICIAL_SEASONAL_SOURCE_KEY,
  OFFICIAL_SEASONAL_SOURCE_LABEL,
  OFFICIAL_SEASONAL_SOURCE_DISPLAY_NAME,
  OFFICIAL_SEASONAL_SOURCE_TYPE,
  OFFICIAL_SEASONAL_CAMPAIGN_TYPE,
  TOTD_SOURCE_KEY,
  TOTD_SOURCE_LABEL,
  TOTD_SOURCE_DISPLAY_NAME,
  TOTD_SOURCE_TYPE,
  TOTD_CAMPAIGN_TYPE,
  WEEKLY_GRANDS_SOURCE_KEY,
  WEEKLY_GRANDS_SOURCE_LABEL,
  WEEKLY_GRANDS_SOURCE_DISPLAY_NAME,
  WEEKLY_GRANDS_SOURCE_TYPE,
  WEEKLY_GRANDS_CAMPAIGN_TYPE,
  COMPETITION_SOURCE_KEY,
  COMPETITION_SOURCE_LABEL,
  COMPETITION_SOURCE_DISPLAY_NAME,
  COMPETITION_SOURCE_TYPE,
  COMPETITION_CAMPAIGN_TYPE,
  COMPETITION_SOURCE_CLUB_ID,
  DISCOVERY_SOURCE_KEY,
  DISCOVERY_SOURCE_LABEL,
  DISCOVERY_SOURCE_DISPLAY_NAME,
  DISCOVERY_SOURCE_TYPE,
  DISCOVERY_CAMPAIGN_TYPE,
  DISCOVERY_SOURCE_CLUB_ID,
  DISCOVERY_SOURCE_CAMPAIGNS,
  LEGACY_SOURCE_KEY,
  LEGACY_SOURCE_LABEL,
  LEGACY_SOURCE_DISPLAY_NAME,
  LEGACY_SOURCE_TYPE,
  LEGACY_CAMPAIGN_TYPE,
  LEGACY_SOURCE_CLUB_ID,
  LEGACY_SOURCE_CAMPAIGNS,
  OFFICIAL_SEASONAL_SOURCE_MAX_AGE_MS,
  PROJECT_SOURCE_RELEASE_BUFFER_MS,
  PROJECT_SOURCE_SCHEDULES,
  DEFAULT_WEEKLY_SHORTS_IMPORT_WEEKS,
  NAMING_SIMILARITY_SOURCE_OPTIONS,
};
